### ISSUE TITLE
Migrate holdmail-ui-vue into this project

### ISSUE THREAD

**Issue by tsneed290** [SpartaSystems/holdmail#39]
### Issue Overview

Per #6, it was agreed to move the UI to Vue.js. A separate project exists https://github.com/SpartaSystems/holdmail-ui-vue which will be migrated into this project.

### Todo

- [x] Upgrade dependencies in holdmail-ui-vue
- [x] Remove modal experience as requested in #36 
- [x] Open links in emails to new tab #11 
- [x] Migrate the Vue UI into holdmail
- [x] (Stretch) Achieve some level of separation between UI and server
- [x] Bring back mail forwarding in the new message details UX
- [x] Update README with UI dev mode instructions

**Comment by tsneed290** [comment]
Bulk of the changes are in master, need to bring back mail forwarding.
